name: wayxec
description: Wayland application launcher.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # wayland_layer_shell: ^1.0.1
  wayland_layer_shell:
    path: ./packages/wayland_layer_shell
  freedesktop_desktop_entry:
    path: ./packages/freedesktop_desktop_entry
  icon_lookup:
    path: ./packages/icon_lookup
  rresvg:
    path: ./packages/rresvg
  fuzzy_string:
    path: ./packages/fuzzy_string
  path: ^1.8.3
  sembast: ^3.6.0
  json_annotation: ^4.9.0
  dbus: ^0.7.11
  args: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
